url: 'https://vguigue.github.io/tuto-LLM/' # your main domain
show_downloads: true
baseurl: ''
plugins:
- jekyll-remote-theme 
remote_theme: pages-themes/cayman
title: "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tutoriel sur l'usage des mod√®les de langue"
